### ISSUE TITLE
node client.js manage shared mods add occassionally fails

### ISSUE THREAD

**Issue by ElGauchooooo** [clusterio/factorioClusterio#229]
I've written a small script that instanciates a bunch of clusterio slaves using Amazons AWS EC2. Among other commands, i've set up the script to download a bunch of scripts using the described method 

`node client.js manage shared mods add <modname>`

The script is downloading several mods (about 15 in total), and ocassionally hangs, e.g.:

```
echo "---Starting downloading mod clusterio---"
str=`sudo -u ubuntu node client.js manage shared mods add clusterio`
if [[ $str =~ "Mod downloaded" ]]; then
    echo "Finished downloading this mod."
fi
echo "---Starting downloading mod bobassembly---"
str=`sudo -u ubuntu node client.js manage shared mods add bobassembly`
if [[ $str =~ "Mod downloaded" ]]; then
    echo "Finished downloading this mod."
fi
echo "---Starting downloading mod bobequipment---"
[...]
```

The whole script is being set as userdata, so it will execute upon ec2 instance creation. The output looks like:

```
---Starting downloading mod clusterio---
Finished downloading this mod.
---Starting downloading mod bobassembly---
```

Then it stops. It occurs randomly, everytime on a different mod. My clusterio cluster contains currently 12 instances of servers, everytime i start the cluster 2-3 out of 12 fail to start. Any clues whats going wrong / how to debug it?

**Comment by Hornwitser** [comment]
Your script doesn't show the output of `node client.js manage shared mods add ...`, if it's outputing an error message before hanging.  I suggest you change it to not storing the output into a string or maybe add `| tee /dev/stderr` inside the backticks.

Unrelated, but if that's your actual code you might want to look into how for loops and variable substitutions work in shell scripts.

**Comment by ElGauchooooo** [comment]
Thanks for the fast reply.

I finally was able to capture the issue, looks like that the mod_cache.json contains some invalid json:

```
{ Error: JSON parsing failed while reading /factorioClusterio/mod_cache.json [SyntaxError: Unexpected end of JSON input]
    at makeNicerJsonParsingError (/factorioClusterio/node_modules/fs-jetpack/lib/read.js:38:22)
    at fs.readFile.then.data (/factorioClusterio/node_modules/fs-jetpack/lib/read.js:106:18)
    at <anonymous>
  originalError: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at fs.readFile.then.data (/factorioClusterio/node_modules/fs-jetpack/lib/read.js:99:26)
    at <anonymous> }
```

right after trying to download the mod.

**Comment by Danielv123** [comment]
That sounds like a race condition. Basically, the library caches all the mods on the portal for a period as its a lot of JSON. I think you might be calling multiple instances of the downloading function at once, causing it to try to read the cache before its fully written by the process that used it last. This can probably be fixed by adding some delay in your script, but should also be fixed in the library/our code.

**Comment by ElGauchooooo** [comment]
Actually, i'm only spawning once instance of clusterio per aws ec2 instance, so no race condition should occur, and (in this case), it immediatelly fails on the first mod (clusterio itself) to download. I'll try to reproduce and check, what is actually breaking the json.

**Comment by ElGauchooooo** [comment]
I've minified the problem down to this script:

```#!/bin/bash
clear
echo "---clearing old cache---"
rm /factorioClusterio/mod_cache.json
echo "---Starting downloading mod---"
node client.js manage shared mods add clusterio
echo "---End downloading mod"```

Running it a couple of times, everything works well until the n-th try (usually after like 10-15 retries), then the cache got invalid. _However_, restarting the script right after it failed (without remotinv the mod cache), everything works fine again. It really looks like that the cache hasn't been written and is already accessed, before writing finished. Can you reproduce this issue aswell?

**Comment by Hornwitser** [comment]
I see the issue now.  node-factorio-client is asynchronously writing the mod cache in the background after the authenticate method promise has resolved (see [this line in the source](https://gitlab.com/Danacus/node-factorio-api/blob/41bf5192d7e866a45381722b9bb499dfa83a54f3/src/node-factorio-api.js#L107)).  Unfortunately not much to be done about that here.

**Comment by ElGauchooooo** [comment]
Are you going to create an issue there or shall i do?
Any ideas for a decent workaround?

**Comment by psihius** [comment]
This is an issue, I'll assign proper labels to it

**Comment by Danielv123** [comment]
A big delay (say 3 -5 seconds) would probably work. You could also write your downloader as  a single nodejs script, that way the library would only try to save one copy of the cache file.

**Comment by Hornwitser** [comment]
I have [posted the issue to the node-factorio-api repo](https://gitlab.com/Danacus/node-factorio-api/issues/10).  Waiting 5 seconds after doing authenticate may be a viable workaround, I'll look into it.
